#!/usr/bin/env ruby

# gem install roo --version 2.7.1

require 'roo'
require 'yaml'
require 'csv'

name = ARGV[0]
raise "no 'name' specified" unless name

# load spse csv (created by 'new')
idx = {}
csv = CSV.new(STDIN.read).read
csv.each {|row| i = idx[row[3]] = row }   # 3 = "Prijmeni Jmeno"

# load ods exported from moodle
ods = Roo::Spreadsheet.open("#{name}.ods")
sheet = ods.sheet(0)
row = sheet.row(1)
row[0] == 'Křestní jméno' or raise "expected Krestni jmeno"
row[2] == 'Příjmení' or raise "expected Prijmeni"

# load tasks
config = YAML::load_file("#{name}.yml")

out = []
config['tasks'].each do |task, defs|

  col_num = sheet.row(1).index {|x| x =~ /#{task}/i } or raise "no matching column for '#{task}' found in the exported ods"

  2.upto(sheet.last_row) do |row_num|
    row = sheet.row(row_num)

    full_name = "#{row[2]} #{row[0]}"
    next unless idx.has_key?(full_name)

    entry = idx[full_name].dup

    score = if row[col_num] == '-'
      'N'
    else
      max = defs['max'] || 100
      pct = row[col_num] / max
      if pct>=0.9
        1
      elsif pct>=0.7
        2
      elsif pct>=0.5
        3
      elsif pct>=0.4
        4
      else
        5
      end
    end

    # ["C3A", "PSS", "virva", "Virva Filip", , "cviceni/teorie", "popis", "1-2-3-4-5-N", "small/big"]
    entry[4] = nil
    entry[5] = config['type']
    entry[6] = task
    entry[7] = score
    entry[8] = defs['weight']

    out << entry

  end

end

puts out.map(&:to_csv).join
